
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/circle-ci-challenge
    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
      - run: npm install
      - save_cache:
         paths:
           - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
         fingerprints:
           - "3e:17:59:7b:15:7d:27:31:fa:49:a9:b9:e4:89:7e:c3"
      - deploy:
         name: Deploy Master to Heroku
         command: |
           if [ "${CIRCLE_BRANCH}" == "master" ]; then
             git push heroku master --force
             heroku run npm start deploy
             heroku restart
           fi
